stages:
#  - test
  - build_docker_image
  - deploy

# Template to build to docker image
.build:
  stage: build_docker_image
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t ${CONTAINER_IMAGE} --no-cache .
    - docker push ${CONTAINER_IMAGE}
    - docker rmi ${CONTAINER_IMAGE}
    - docker logout $CI_REGISTRY

# Template to deploy to WP k8s cluster

.deploy-wp-feature:
  stage: deploy
  image: dockerhub.ebi.ac.uk/kamal/deploy-tools:0.1

  script:
  - git clone https://gitlab.ebi.ac.uk/kamal/ensembl-client-caas-deploy.git
  - git -C ensembl-client-caas-deploy/ checkout ensembl_refget_proxy_caas_deploy
  - sed -i "s#<DOCKER_IMAGE>#${CONTAINER_IMAGE}#g" ensembl-client-caas-deploy/ensembl_refget_proxy_deployment.yaml
  - sed -i "s#<DEPLOYMENT_ENV>#${CI_COMMIT_REF_SLUG}#g" ensembl-client-caas-deploy/ensembl_refget_proxy_deployment.yaml
  - sed -i "s#<DEPLOYMENT_ENV>#${CI_COMMIT_REF_SLUG}#g" ensembl-client-caas-deploy/ensembl_refget_proxy_service.yaml
  - kubectl apply -f ensembl-client-caas-deploy/ensembl_refget_proxy_service.yaml
  - kubectl apply -f ensembl-client-caas-deploy/ensembl_refget_proxy_deployment.yaml
  variables:
    DOCKERFILE: Dockerfile.prod
    DOCKER_TLS_CERTDIR: ""

# Run Tests
#Test:
#  stage: test
#
#  image: python:3.7.2
#
#  script:
#    - python -m unittest discover -s tests

# Build docker image for feature_branch environment

Docker-IMG:feature:
  extends: .build
  variables:
    CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    DOCKERFILE: Dockerfile.feature

  only:
  - /^feature\/.*$/
  - /^refactor\/.*$/
  when: manual


Feature:EHK-HH:
  extends: .deploy-wp-feature
  variables:
    CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_SLUG}
    DEPLOY_TAG: ${CI_COMMIT_REF_SLUG}
    KUBE_CONTEXT: ens-dev-ctx
  only:
  - /^feature\/.*$/
  when: manual
