variables:
    DOCKER_TLS_CERTDIR: ""
    CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}

stages:
  - test
  - build_docker_image
  - deploy
  - compliance

# Template to build to docker image
.build:
  stage: build_docker_image
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t ${CONTAINER_IMAGE} --no-cache .
    - docker push ${CONTAINER_IMAGE}
    - docker rmi ${CONTAINER_IMAGE}
    - docker logout $CI_REGISTRY

# Template to deploy to WP k8s cluster

.deploy-wp-feature:
  stage: deploy
  image: dockerhub.ebi.ac.uk/kamal/deploy-tools:0.1

  script:
  - git clone https://gitlab.ebi.ac.uk/kamal/ensembl-client-caas-deploy.git
  - git -C ensembl-client-caas-deploy/ checkout ensembl_refget_proxy_caas_deploy
  - sed -i "s#<DOCKER_IMAGE>#${CONTAINER_IMAGE}#g" ensembl-client-caas-deploy/ensembl_refget_proxy_deployment.yaml
  - sed -i "s#<DEPLOYMENT_ENV>#${CI_COMMIT_REF_SLUG}#g" ensembl-client-caas-deploy/ensembl_refget_proxy_deployment.yaml
  - sed -i "s#<DEPLOYMENT_ENV>#${CI_COMMIT_REF_SLUG}#g" ensembl-client-caas-deploy/ensembl_refget_proxy_service.yaml
  - kubectl apply -f ensembl-client-caas-deploy/ensembl_refget_proxy_deployment.yaml
  - kubectl apply -f ensembl-client-caas-deploy/ensembl_refget_proxy_service.yaml
  variables:
    DOCKERFILE: Dockerfile.prod

# Run Tests
Test:
  stage: test

  image: python:3.8

  variables:
    REFGET_SERVER_URL_LIST: $REFGET_SERVER_URL_LIST
  script:
    - pip install poetry==1.0.*
    - poetry config virtualenvs.create false
    - poetry install --no-dev
    - cp -R ./app/ /app/
    - cd /app
    - python -m unittest


Compliance-Test:
  stage: compliance
  image: python:3.8
  script:
    - pip install refget-compliance
    - refget-compliance report -s http://dev.refget.review.ensembl.org /api/ --json server.json
    - cat server.json

Docker-IMG:feature:
  extends: .build
  variables:
    DOCKERFILE: Dockerfile.feature

  only:
  - /^feature\/.*$/
  - /^refactor\/.*$/
  when: manual


Feature:wp-feature:
  extends: .deploy-wp-feature
  variables:
    DEPLOY_TAG: ${CI_COMMIT_REF_SLUG}
  environment:
    name : hx
  only:
  - /^feature\/.*$/
  when: manual
