version: '2'
services:
  refget_proxy:

    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - REFGET_SERVER_URL_LIST=${REFGET_SERVER_URL_LIST}
      - DEBUG=${DEBUG}
    container_name: refget_proxy_api
    volumes:
      - ./app/:/app/
    ports:
      - 8083:8083
