apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ensembl-refget-proxy-redis-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ensembl-refget-proxy-redis-deployment
        RUP: nickl
    spec:
      containers:
      - name: ensembl-refget-proxy-redis
        image: dockerhub.ebi.ac.uk/mcharkhchi/ensembl-refget-proxy-redis:v0.1
        ports:
        - containerPort: 6379
        imagePullPolicy: Always
