apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ensembl-refget-proxy-redis-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ensembl-refget-proxy-redis
        RUP: nickl
    spec:
      containers:
      - name: ensembl-refget-proxy-redis
        image: redis:6.2.4
        ports:
        - containerPort: 6379
        imagePullPolicy: Always
