apiVersion: v1
kind: Service
metadata:
  name: ensembl-solr-search-svc
  labels:
    app: ensembl-solr-search-svc
spec:
  selector:
    app: ensembl-solr-search
  type: ClusterIP
  ports:
    - port: 8983
      protocol: TCP
      targetPort: 8983