apiVersion: v1
kind: Service
metadata:
  name: ensembl-refget-proxy-node-svc
  labels:
    app: ensembl-refget-proxy-node-svc
spec:
  selector:
    app: ensembl-refget-proxy
  type: NodePort
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083